modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="new_generation"
version="0.0.2"
displayName="New Generation"
displayURL="https://mcreator.net"
credits="MCreator, TygrysGamesYT"
authors="TygrysGamesYT, MCreator"
description="New Generation is mod for minecraft that is exteme intresting..."

[[dependencies.new_generation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




